### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by stcalica** [ethereum/eth-account#133]
## What was wrong?

When importing eth_account, I get the error that the module Cryto is not found. 
I am on `OSX Big Sur` and  my python version is `v3.8`
I have installed these crypto packages: 

```sh
crypto==1.4.1
pycrypto==2.6.1
pycryptodome==3.11.0
```
Seems to be an issue with Crypto library being imported and capitalized?  

### Code that produced the error

```py
from eth_account.messages import defunct_hash_message 
```

### Full error output 

```sh
Traceback (most recent call last):
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kcelica/Code/Django-for-web3/core/auth/backends.py", line 2, in <module>
    from eth_account.messages import defunct_hash_message
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/eth_account/account.py", line 11, in <module>
    from eth_keyfile import (
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/Users/kcelica/Code/Django-for-web3/env/lib/python3.8/site-packages/eth_keyfile/keyfile.py", line 5, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

```

### Expected Result
I see others have fixed their issue by *manually* editing their file names in `site-packages` but this is not a long-term solution or makes it easy to use this code anywhere especially when deployed in a CI/CD setup. 

### Environment

```sh
# run this:
$ python -m eth_utils

# then copy the output here:
$  python -m eth_utils
Python version:
3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
[Clang 6.0 (clang-600.0.57)]

Operating System: macOS-10.16-x86_64-i386-64bit

pip freeze result:
aiohttp==3.8.1
aiosignal==1.2.0
asgiref==3.4.1
async-timeout==4.0.1
attrs==21.2.0
base58==2.1.1
bitarray==1.2.2
certifi==2021.10.8
charset-normalizer==2.0.7
crypto==1.4.1
cytoolz==0.11.2
Django==3.2.8
django-cors-headers==3.10.0
djangorestframework==3.12.4
djangorestframework-simplejwt==5.0.0
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
frozenlist==1.2.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.2.0
Naked==0.1.31
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.19.1
pycrypto==2.6.1
pycryptodome==3.11.0
PyJWT==2.3.0
pyrsistent==0.18.0
pytz==2021.3
PyYAML==6.0
requests==2.26.0
rlp==2.0.1
shellescape==3.8.1
six==1.16.0
sqlparse==0.4.2
toolz==0.11.2
typing_extensions==4.0.0
urllib3==1.26.7
varint==1.0.2
web3==5.25.0
websockets==9.1
yarl==1.7.2
```

**Comment by kclowes** [comment]
I see this line: `from Crypto import Random` in eth-keyfile, but I'm not able to replicate the `ModuleNotFoundError` when I do the following steps in a fresh virtualenv: 
```
$ pip install eth_account
$ pip install ipython
$ ipython
>>> from eth_account.messages import defunct_hash_message
```
Is there another way to reproduce?

**Comment by stcalica** [comment]
@kclowes  I've read this may only happen on certain Macs? 
I don't know what you are using but I am on OSX Big Sur. 
I would try to install all my dependencies above into a fresh env. 
Maybe something is clashing? 
I'll try to do the same rn.

**Comment by stcalica** [comment]
I am able to get it to work by using pycryptodome and using easy_install over pip3
Suggested from here: 
https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher

But wonder why this happens

**Comment by kclowes** [comment]
> I've read this may only happen on certain Macs?
I don't know what you are using but I am on OSX Big Sur.

I'm not sure. I am running Big Sur as well, so I don't think that's the problem. I suspect there is some dependency conflict somewhere, but don't really have a better answer. Going to close since you figured it out, but feel free to reopen if you think there is a bug we can fix.
