### ISSUE TITLE
encode_structured_data Error with Array Types (SignTypedDataV4)

### ISSUE THREAD

**Issue by Exoceus** [ethereum/eth-account#149]
## What was wrong?

`encode_structured_data` throws KeyError when there is an array type in a struct. The error doesn't give any context and seems to support some array types (ex. `Person[]` doesnt seem to throw error but `address[]` throws error).  When I simply just make the Person.wallets to be `address` instead of `address[]` it works (obviously I update the message accordingly). But for some reason, an array of address just is not working. For more context, I am trying to make it work with the SignTypedDataV4 on MetaMasks[ test Dapp](https://metamask.github.io/test-dapp/)

### Code that produced the error

```py
msg = {
      'domain': {
        'chainId': 1,
        'name': 'Ether Mail',
        'verifyingContract': '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC',
        'version': '1',
      },
      'message': {
        'contents': 'Hello, Bob!',
        'from': {
          'name': 'Cow',
          'wallets': ['0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826',
                      '0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826'],
        },
        'to': [
          {
            'name': 'Bob',
            'wallets': ['0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826',
                        '0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826'],
          },
        ],
      },
      'primaryType': 'Mail',
      'types': {
        'EIP712Domain': [
          { 'name': 'name', 'type': 'string' },
          { 'name': 'version', 'type': 'string' },
          { 'name': 'chainId', 'type': 'uint256' },
          { 'name': 'verifyingContract', 'type': 'address' },
        ],
        'Group': [
          { 'name': 'name', 'type': 'string' },
          { 'name': 'members', 'type': 'Person[]' },
        ],
        'Mail': [
          { 'name': 'from', 'type': 'Person' },
          { 'name': 'to', 'type': 'Person[]' },
          { 'name': 'contents', 'type': 'string' },
        ],
        'Person': [
          { 'name': 'name', 'type': 'string' },
          { 'name': 'wallets', 'type': 'address[]' },
        ],
      },
    }
  
    new_msg = json.loads(json.dumps(msg), object_hook=_decode)
    new_msg['domain']['version'] = str(new_msg['domain']['version'])
    encoded_msg = encode_structured_data(new_msg)
    signed_msg = w3.eth.account.sign_message(encoded_msg, account)
```

### Full error output 

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/sign_message.py", line 158, in t 
    encoded_msg = encode_structured_data(new_msg)
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/messages.py", line 156, in encode_structured_data
    hash_eip712_message(structured_data),
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 286, in hash_message
    encode_data(
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 262, in encode_data
    data_types_and_hashes = _encode_data(primaryType, types, data)
  File "/home/user/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 209, in _encode_data
    hashed_value = keccak(primitive=encode_data(field["type"], types, value))
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 262, in encode_data
    data_types_and_hashes = _encode_data(primaryType, types, data)
  File "/home/user/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 232, in _encode_data
    array_items_encoding = [
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 233, in <listcomp>
    encode_data(parsed_type.base, types, array_item)
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 262, in encode_data
    data_types_and_hashes = _encode_data(primaryType, types, data)
  File "/home/user/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 174, in _encode_data
    yield "bytes32", hash_struct_type(primary_type, types)
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 96, in hash_struct_type
    return keccak(text=encode_type(primary_type, types))
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 83, in encode_type
    deps = get_dependencies(primary_type, types)
  File "/home/user/.local/lib/python3.8/site-packages/eth_account/_utils/structured_data/hashing.py", line 40, in get_dependencies
    fields = types[struct_name]
KeyError: 'address'
```

### Environment

```sh
Python version:
3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

Operating System: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29

pip freeze result:
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==19.3.0
Automat==0.8.0
base58==2.1.1
bitarray==1.2.2
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
charset-normalizer==2.0.12
click==8.0.4
cloud-init==20.1
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
cytoolz==0.11.2
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
dnspython==2.2.0
entrypoints==0.3
eth-abi==3.0.0
eth-account==0.6.1
eth-hash==0.3.2
eth-keyfile==0.6.0
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.0.0
eth-utils==2.0.0
Flask==2.0.1
Flask-Cors==3.0.10
frozenlist==1.3.0
hexbytes==0.2.2
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
ipfshttpclient==0.8.0a2
itsdangerous==2.1.0
Jinja2==3.0.3
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lru-dict==1.1.7
MarkupSafe==2.1.0
more-itertools==4.2.0
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
netifaces==0.10.4
oauthlib==3.1.0
parsimonious==0.8.1
protobuf==3.19.4
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycryptodome==3.14.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
pymongo==3.11.4
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.0
python-debian===0.1.36ubuntu1
python-dotenv==0.19.2
PyYAML==5.3.1
requests==2.25.1
requests-unixsocket==0.2.0
rlp==3.0.0
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.16.0
ssh-import-id==5.10
stripe==2.66.0
systemd-python==234
toolz==0.11.2
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
varint==1.0.2
wadllib==1.3.3
web3==5.28.0
websockets==9.1
Werkzeug==2.0.3
yarl==1.7.2
zipp==1.0.0
zope.interface==4.7.1
``` 

## How can it be fixed?

Unsure of how to solve it

**Comment by ymmmmmmmm** [comment]
Encountered the same problem, hope add support for arrays
https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4
https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

**Comment by jvinet** [comment]
From what I can see by reading the code, it does support arrays for user-defined ABI types, but not for native types (eg, `bytes`, `uint256`, etc).

**Comment by leykun10** [comment]
> From what I can see by reading the code, it does support arrays for user-defined ABI types, but not for native types (eg, `bytes`, `uint256`, etc).

what can we do about native types(like bytes32), any workaround?

**Comment by jvinet** [comment]
@leykun10, this patch makes the code stop throwing `KeyError`, can you see if it also works for you?  I'm not sure if it's logically correct yet, however.

```
--- eth-account/eth_account/_utils/structured_data/hashing.py      2022-06-08 12:13:24.483785022 -0400
+++ patched/eth_account/hashing.py 2022-04-13 19:03:06.767846376 -0400
@@ -229,10 +229,14 @@
                     )

             array_items = flatten_multidimensional_array(value)
-            array_items_encoding = [
-                encode_data(parsed_type.base, types, array_item)
-                for array_item in array_items
-            ]
+            if parsed_type.base in types.keys():
+                array_items_encoding = [
+                    encode_data(parsed_type.base, types, array_item)
+                    for array_item in array_items
+                ]
+            else:
+                array_items_encoding = [encode_abi((parsed_type.base,), (el,))
+                                        for el in array_items]
             concatenated_array_encodings = b''.join(array_items_encoding)
             hashed_value = keccak(concatenated_array_encodings)
             yield "bytes32", hashed_value
```

**Comment by pacrob** [comment]
Hey, @Exoceus, PR #175 should take care of the problems you were having here. If you get a chance, please try your use-case against it and let us know if you're still seeing issues.
