### ISSUE TITLE
Support for native types like bytes with encode_structured_data

### ISSUE THREAD

**Issue by leykun10** [ethereum/eth-account#158]
## What was wrong?
Object of type bytes is not JSON serializable
### Code that produced the error
msg = {'types': {'EIP712Domain': [{'name': 'name', 'type': 'string'}, {'name': 'version', 'type': 'string'}, {'name': 'chainId', 'type': 'uint256'}, {'name': 'verifyingContract', 'type': 'address'}], 'Withdraw': [{'name': 'id', 'type': 'bytes32'}, {'name': 'amount', 'type': 'uint128'}]}, 'domain': {'name': 'DemoApp', 'version': '1.0.0', 'chainId': 4, 'verifyingContract': '0x5794f10bB0810Bd433B3a641BA21067354CA1510'}, 'primaryType': 'Withdraw', 'message': {'id': b'0xEB5bC0F5d09C59F9619bE9a92fd0A830Bea6a8F4', 'amount': 0}}
encoded_data=encode_structured_data(msg)

```


CODE_TO_REPRODUCE 
```

### Full error output 
Internal Server Error: /payments/withdraw
django-backend_1  | Traceback (most recent call last):
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
django-backend_1  |     response = get_response(request)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
django-backend_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django-backend_1  |     return view_func(*args, **kwargs)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
django-backend_1  |     return self.dispatch(request, *args, **kwargs)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
django-backend_1  |     response = self.handle_exception(exc)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
django-backend_1  |     self.raise_uncaught_exception(exc)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django-backend_1  |     raise exc
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
django-backend_1  |     response = handler(request, *args, **kwargs)
django-backend_1  |   File "/BlockChain-Management-Api/payment_module/views.py", line 138, in post
django-backend_1  |     signature,signer=withdrawSignature(request.data)
django-backend_1  |   File "/BlockChain-Management-Api/payment_module/helpers.py", line 184, in withdrawSignature
django-backend_1  |     signature,signer=getSignature(data,"Withdraw")
django-backend_1  |   File "/BlockChain-Management-Api/payment_module/signature_functions.py", line 56, in getSignature
django-backend_1  |     sig = smart_contract_utils.generateSignature(defaults["privateKey"],SignatureTypes.Structured,msg)
django-backend_1  |   File "/BlockChain-Management-Api/smart_contract_sdk/smart_contract_utils.py", line 126, in generateSignature
django-backend_1  |     encoded_data=encode_structured_data(msg)
django-backend_1  |   File "/usr/local/lib/python3.8/site-packages/eth_account/messages.py", line 146, in encode_structured_data
django-backend_1  |     message_string = json.dumps(primitive)
django-backend_1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
django-backend_1  |     return _default_encoder.encode(obj)
django-backend_1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
django-backend_1  |     chunks = self.iterencode(o, _one_shot=True)
django-backend_1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
django-backend_1  |     return _iterencode(o, 0)
django-backend_1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
django-backend_1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
django-backend_1  | TypeError: Object of type bytes is not JSON serializable

**Comment by leykun10** [comment]
https://github.com/ethereum/eth-account/issues/90#issue-560579934
