### ISSUE TITLE
Unable to retrieve acct key 

### ISSUE THREAD

**Issue by rite2bala** [ethereum/eth-account#70]
Faced a problem while following the instructions on https://buildmedia.readthedocs.org/media/pdf/eth-account/latest/eth-account.pdf

```
from eth_account import Account
acct = Account.create('KEYSMASH FJAFJKLDSKF7JKFDJ 1530')
acct.address  
acct.key
Traceback (most recent call last):

  File "<ipython-input-12-352e77122c2d>", line 4, in <module>
    acct.key

**AttributeError: 'LocalAccount' object has no attribute 'key'**
```

Although the account gets created , I am unable to retrieve the key as shown in the introductory documents ..

Could you please let me know how I can retrieve the private key for the account which got created?
Or am i doing  something wrong?

**Comment by carver** [comment]
What version of `eth-account` do you have installed?

**Comment by AndreMiras** [comment]
I can reproduce the issue in **0.3.0** only, **0.4.0** and **master** are fine:
```
[andre:~/workspace/eth-account] [venv] a1e5ab2+* ± git checkout v0.4.0
HEAD is now at a1e5ab2 Bump version: 0.3.0 → 0.4.0
[andre:~/workspace/eth-account] [venv] a1e5ab2+* ± python -c "from eth_account import Account; print(Account.create('').key)"
b'\xfaV\x84b4\xd3\xcf\x01\xe1H\xa7\x1c{_a\xe9B\x18\xfc\xae\x94w\x96\xce\xfd\x8a\x0ez\xc1r\x02"'
[andre:~/workspace/eth-account] [venv] a1e5ab2+* ± git checkout v0.3.0
Previous HEAD position was a1e5ab2 Bump version: 0.3.0 → 0.4.0
HEAD is now at 3ac5aed Bump version: 0.2.3 → 0.3.0
[andre:~/workspace/eth-account] [venv] 3ac5aed+* ± python -c "from eth_account import Account; print(Account.create('').key)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'LocalAccount' object has no attribute 'key'
[andre:~/workspace/eth-account] [venv] 3ac5aed+* 1 ± git checkout upstream/master
Previous HEAD position was 3ac5aed Bump version: 0.2.3 → 0.3.0
HEAD is now at 9bcc910 Merge pull request #74 from kclowes/remove-collections-deprecation-warning
[andre:~/workspace/eth-account] [venv] 9bcc910+* ± python -c "from eth_account import Account; print(Account.create('').key)"
b'\xa70\xd8\x90\x1aP,<\x95\xfa\n\x94\xcd\xe2\xdf\xf6n+\x91"\x9d\xaa?{2\xb9\x0eN:n\x0b4'
[andre:~/workspace/eth-account] [venv] 9bcc910+* ±
```

**Comment by carver** [comment]
Closing as resolved. Feel free to re-open if we missed something!
